#!/bin/bash
# Rollback production site changes

if [ $# -eq 0 ]; then
  echo ""
  echo "Command error. Usage: script/rollback <commit-hash>"
  echo "where <commit-hash> should have been provided by the script/deploy command."
  echo ""
  exit 1
fi

COMMIT_HASH=$1

set -e
echo "This will update the live website to an older version (commit $COMMIT_HASH)."
echo "Type 'ok' to continue (or 'no' to cancel): "

while read VAR_OK; do
  if [ "$VAR_OK" == "ok" ]
  then
    break
  fi
  if [ "$VAR_OK" == "no" ]
  then
    echo "You've chosen to cancel. Bye."
    echo ""
    exit 0
  fi
  echo "You must type 'ok' to proceed or 'no' to cancel:"
done

echo "Rolling back live website to commit $COMMIT_HASH..."

echo "$(tput setaf 1)ERROR: Rollback is not implemented yet. Sorry!$(tput sgr 0)"
exit 1

#ssh ruptests@ptws-staging-rupeal "cd ~/git-ruptests.git; git reset --hard $COMMIT_HASH"
#git push ptws master
echo ""
echo "$(tput setaf 2)Done.$(tput sgr 0). The live site should have been updated."
echo ""
